default_job = "clippy"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy]
command = ["cargo", "+esp", "clippy"]
need_stdout = false

[jobs.run]
command = ["cargo", "+esp", "run"]
need_stdout = true
allow_warnings = true
background = true
